version: '3.6'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#     IMPORTANT: DO NOT USE THESE SETTINGS IN THE ACTUAL PRODUCTION SERVER.
  website:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:  sh -c "pip install --no-cache-dir -r requirements.txt &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - './backend:/usr/src/website'
    ports:
      - "8000:8000"
    depends_on:
      - db
