# Generated by Django 3.2.7 on 2021-09-08 17:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrainfo',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 17, 5, 22, 26510)),
        ),
        migrations.AlterField(
            model_name='userextrainfo',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userextrainfo',
            name='discord_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userextrainfo',
            name='forum_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userextrainfo',
            name='home_origin',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='userextrainfo',
            name='in_game_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
