# Generated by Django 3.2.7 on 2021-09-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userextrainfo_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
