# Generated by Django 3.2.7 on 2021-10-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210921_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextrainfo',
            name='registered_on',
        ),
    ]
