# Generated by Django 3.2.7 on 2021-09-15 09:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ship_images')),
                ('description', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(default='', max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=6000, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_blueprint', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='shipshop.ShipImage')),
            ],
        ),
        migrations.CreateModel(
            name='ShipWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlisted_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipshop.shipentry')),
            ],
            options={
                'unique_together': {('user', 'wishlisted_ship')},
            },
        ),
        migrations.CreateModel(
            name='ShipLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipshop.shipentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'liked_ship')},
            },
        ),
    ]
