# Generated by Django 3.2.7 on 2021-09-10 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipshop', '0002_auto_20210908_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipentry',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shipentry',
            name='price_blueprint',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
