# Generated by Django 3.2.7 on 2021-09-13 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipshop', '0003_auto_20210910_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipentry',
            name='images',
            field=models.ManyToManyField(blank=True, to='shipshop.ShipImage'),
        ),
        migrations.AlterField(
            model_name='shipentry',
            name='ship_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='ShipWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlisted_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipshop.shipentry')),
            ],
            options={
                'unique_together': {('user', 'wishlisted_ship')},
            },
        ),
    ]
