# Generated by Django 3.2.7 on 2021-10-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0004_faction_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='faction_tag',
            field=models.CharField(default='', max_length=4),
        ),
    ]
