# Generated by Django 3.2.8 on 2021-10-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0005_faction_faction_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='faction_tag',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
