# Generated by Django 3.2.7 on 2021-09-19 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=20000, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FactionAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faction_advertisements')),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('is_embed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FactionEmblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faction_emblems')),
            ],
        ),
        migrations.CreateModel(
            name='FactionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction')),
                ('roles', models.ManyToManyField(blank=True, to='factions.FactionRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='advertisement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factions.factionadvertisement'),
        ),
        migrations.AddField(
            model_name='faction',
            name='emblem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factions.factionemblem'),
        ),
        migrations.AddField(
            model_name='faction',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leading_faction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faction',
            name='members',
            field=models.ManyToManyField(blank=True, through='factions.FactionMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faction',
            name='roles',
            field=models.ManyToManyField(blank=True, to='factions.FactionRole'),
        ),
    ]
