# Generated by Django 3.2.7 on 2021-09-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0002_auto_20210923_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='emblem',
        ),
        migrations.DeleteModel(
            name='FactionEmblem',
        ),
    ]
