# Generated by Django 3.2.7 on 2021-09-08 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipimage',
            name='image',
            field=models.ImageField(upload_to='ship_images'),
        ),
        migrations.AlterUniqueTogether(
            name='shiplike',
            unique_together={('user', 'liked_ship')},
        ),
    ]
