# Generated by Django 3.2.7 on 2021-09-19 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipshop', '0004_auto_20210913_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipentry',
            name='like_users',
            field=models.ManyToManyField(related_name='liked_ship', through='shipshop.ShipLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipentry',
            name='wishlist_users',
            field=models.ManyToManyField(related_name='whitelisted_ship', through='shipshop.ShipWishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiplike',
            name='liked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shipwishlist',
            name='wishlisted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shipentry',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ship', to=settings.AUTH_USER_MODEL),
        ),
    ]
