# Generated by Django 3.2.7 on 2021-09-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210921_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
